name: CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch: # manual button in Actions tab
env:
  NODE_ENV: development # you define

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
        if: success()

  notify:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - run: echo "build failed!"
