name: CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch: # manual button in Actions tab
env:
  NODE_ENV: development # you define

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GREETING: Hello
    steps:
      - run: echo "Hi ${{ github.actor }} on ${{ github.ref }}" # github context
      - run: echo ${{ env.GREETING }} # env context
      - run: echo $GREETING # shell variable (same value, different time)
      - env:
          TOKEN: ${{ secrets.MY_TOKEN }} # secrets context
        run: echo ${#TOKEN}
